/**
 * `Cloudflare.Env` comes from `worker-configuration.d.ts`, generated by
 * `npm run types:worker` (a thin wrapper around `wrangler types --strict-vars=false`)
 * from the bindings and vars in wrangler.jsonc. Re-run it whenever wrangler.jsonc
 * changes instead of hand-editing binding shapes here.
 *
 * DEV_ACCESS_EMAIL is the one field we override: it lives only in .dev.vars
 * (never in wrangler.jsonc, since wrangler deploy never reads that file), so the
 * generator has no way to know it's absent in production and types it as a
 * required string. It has to stay optional here.
 */
export interface Env extends Omit<Cloudflare.Env, "DEV_ACCESS_EMAIL"> {
  DEV_ACCESS_EMAIL?: string;
}
